@url = http://localhost:3000/api 

GET {{url}}/almacenes


###
POST {{url}}/almacenes
Content-Type: application/json

{
  "nombre": "Almacén Central",
  "localizacion": "Sucursal Este"
}


###
POST {{url}}/almacenes
Content-Type: application/json

{
  "nombre": "Almacén Destino",
  "localizacion": "Sucursal Oeste"
}

###
PUT {{url}}/almacenes/1
Content-Type: application/json

{
  "nombre": "Almacén Nuevo",
  "localizacion": "Sucursal Norte"
}


###

DELETE {{url}}/almacenes/2