@url = http://localhost:3000/api 

GET {{url}}/users/

###
POST {{url}}/users
Content-Type: application/json

{
    "nombre": "Jose",
    "apellido": "Lopez",
    "email": "jose@gmail.com",
    "password": "1234",
    "rol": "jefe"
}

###
POST {{url}}/users
Content-Type: application/json

{
    "nombre": "Manuel",
    "apellido": "Gomez",
    "email": "manuel@gmail.com",
    "password": "1234",
    "rol": "encargado"
}


###
PUT {{url}}/users/11
Content-Type: application/json

{
    "nombre": "Antonio",
    "apellido": "Lopez",
    "email": "antonio@gmail.com",
    "password": "1234",
    "rol": "operario"
}



###
DELETE {{url}}/users/11
Content-Type: application/json